CREATE TABLE BENCH
(
    BENCH_ID                     BIGINT NOT NULL,
    BENCH_NAME                   VARCHAR(50) NOT NULL,
    BENCH_RESULT                 VARCHAR(50) NOT NULL,
    CONSTRAINT BENCH_ID_UNIQUE UNIQUE (BENCH_ID)
);

CREATE SEQUENCE BENCH_SEQ;