version: '2'

services:
  app:
    image: 'crud-bench/basic:latest'
    expose:
      - 8080
    ports:
    - 8080:8080
    build:
      context: .
    container_name: crud-bench
    depends_on:
      - db

  db:
    image: 'postgres:13.1-alpine'
    ports:
    - 5432:5432
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres